version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: apimicrodb
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'